# Sign actions.

name: Sign

# Trigger on push or everyday 10:21 AM @ "Asia/Shanghai" Timezone (UTC+8).
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '21 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: tyde7/yqxx_auto_sign@master
        with:
          args: yarn
      - name: Test
        uses: tyde7/yqxx_auto_sign@master
        env: 
          JWC_USERNAME: ${{ secrets.JWC_USERNAME }}
          JWC_PASSWORD: ${{ secrets.JWC_PASSWORD }}
          WECHAT_ROBOT_HOOK: ${{ secrets.WECHAT_ROBOT_HOOK }}
        with:
          args: yarn test
